[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
async-std = { version = "^1", features = ["attributes", "tokio1", ] }
digital_asset_types = { path = "../digital_asset_types", features = ["json_types", "sql_types"] }
[dependencies.sea-orm-migration]
version = "^0.9.0"
features = [
    "runtime-tokio-rustls",
    "sqlx-postgres",
]
