apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load
    {{- include "ingest.labels" . | nindent 4 }}-load
spec:
  replicas: 2
  selector:
    matchLabels:
      app: load
      {{- include "ingest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: load
        {{- include "ingest.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always

      containers:
        - name: load-gen
          image: {{.Values.loadImage}}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: SEED
              value: {{.Values.load.seed}}
            - name: NETWORK
              value: {{.Values.load.network}}
            - name: AMOUNT_OF_CHAOS
              value: {{.Values.load.chaos | quote}}
            - name: RPC_URL
              value: {{.Values.load.rpc_url}}
          readinessProbe:
            initialDelaySeconds: 1
            failureThreshold: 30
            periodSeconds: 60
            exec:
              command:
                - echo
                - "true"
          livenessProbe:
            initialDelaySeconds: 1
            failureThreshold: 30
            periodSeconds: 60
            exec:
              command:
                - echo
                - "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
