apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingest.secret" . }}-migrator
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
data:
  DATABASE_URL: {{ .Values.ingest.db_url | b64enc | quote }}
