apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingest.secret" . }}
data:
  INGESTER_DATABASE_CONFIG: {{ ( printf "{backfill_listener=\"backfill_item_added\", slot_listener=\"slot_processed\", url=\"%s\"}" .Values.ingest.db_url ) | b64enc | quote }}
  INGESTER_MESSENGER_CONFIG: {{ ( printf "{connection_config={redis_connection_str=%s}, messenger_type=\"Redis\"}" .Values.ingest.redis_url ) | b64enc | quote }}
  INGESTER_RPC_CONFIG: {{ ( printf "{url=%s, commitment=\"finalized\"}" .Values.ingest.rpc_url ) | b64enc | quote }}
