[package]
name = "load_generation_candy_machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.14.1", features = ["full"] }
solana-client = "1.10.13"
mpl-candy-machine = {  git = "https://github.com/metaplex-foundation/metaplex-program-library", branch = "stranzhay/read-api", features = ["no-entrypoint"] }
mpl-token-metadata = { version = "1.3.6", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.0.5", features = [
  "no-entrypoint",
] }
spl-token = "3.2.0"
solana-program = "1.10.13"
rand = "0.8.5"
fake = "2.5.0"
anchor-lang = "0.25.0"
anchor-spl = "0.25.0"
solana-sdk = "1.10.13"


[dev-dependencies]
borsh = "~0.9.2"
tarpc = "0.29.0"
console = "0.15.1"